apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: identity-serviceaccount
      containers:
        - name: ssp-identityservice
          image: acrplayeconomydev001.azurecr.io/ssp-identityservice:latest
          imagePullPolicy: Always
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: cosmosdb-connectionstring
            - name: ServiceBusSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: servicebus-connectionstring
            - name: IdentitySettings__AdminUserPassword
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: admin-password
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5002
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health/live
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health/ready
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 5002

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-serviceaccount
  annotations:
    azure.workload.identity/client-id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX
  labels:
    azure.workload.identity/use: "true"
