apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservice-deployment
spec:
  selector:
    matchLabels:
      app: identityservice-app
  template:
    metadata:
      labels:
        app: identityservice-app
    spec:
      containers:
        - name: ssp-identityservice
          image: acrplayeconomydev001.azurecr.io/ssp-identityservice:latest
          env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: cosmosdb-connectionstring
            - name: ServiceBusSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: servicebus-connectionstring
            - name: IdentitySettings__AdminUserPassword
              valueFrom:
                secretKeyRef:
                  name: identity-secrets
                  key: admin-password
          resources:
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: 5002
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5002
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5002
            initialDelaySeconds: 10          

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  selector:
    app: identityservice-app
  ports:
    - port: 80
      targetPort: 5002
